sudo: required
language: cpp

compiler:  
    - gcc

before_install:
  - sudo apt-get update -q


install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5.4" CC="gcc-5.4"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++" CC="clang"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.4
    - g++-5.4
    - clang

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: 
    - make
    - make test  
